### ISSUE TITLE
Deleting Deprecated Data

### ISSUE THREAD

**Issue by ikirshner** [ghostops/react-native-recoil-persist#2]
Hi! 

So, I'm curious what would be the best way to clear data from async local storage when no longer using a piece of state. In other words, we have a deprecated recoil atom from a previous version (that we were persisting via the atom effect in this package), and now we want to make sure that the associated data is cleared from local async storage.

Any thoughts?

Thanks!

**Comment by ghostops** [comment]
Hi, I haven't been maintaining this package for a while. Unfortunately I have no good answer to your question. I think this is outside of the scope for this package, as removing data is a tricky topic.
